### ISSUE TITLE
Bad reference in the .csproj files

### ISSUE THREAD

**Issue by jinnHoward** [jinnstudios/WebApi-FullFramework#1]
this needs to be removed:
`<Error Condition="!Exists('..\..\..\..\..\..\Users\WebFletch\source\repos\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.0\build\net46\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props')" Text="$([System.String]::Format('$(ErrorText)', '..\..\..\..\..\..\Users\WebFletch\source\repos\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.0\build\net46\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props'))" />`

**Comment by jinnstudios** [comment]
Looking at that now.

**Comment by jinnHoward** [comment]
Fixed
